- name: Install app store cli
  community.general.homebrew:
    name: mas
    state: present
  when: mas_packages | bool

- name: Fetch installed from app store
  ansible.builtin.command: mas list
  register: mas_installed_apps
  changed_when: false

- name: Install apps from app store
  ansible.builtin.command: "mas install {{ item.id | default(item) }}"
  changed_when: (item.id | default(item) | string) not in mas_installed_apps.stdout
  loop: "{{ mas_apps }}"
  loop_control:
    label: "{{ item.name | default(item) }}"
